name: otpp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  country_picker: ^2.0.22
  firebase_auth: ^4.12.1
  pinput: ^3.0.1
  flutterfire_cli: ^0.2.7
  firebase_core: ^2.21.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

